[project]
name = "array-api-typing"
version = "0.0.1a1"
requires-python = ">= 3.10"
dependencies = [
    "typing_extensions>=4.5",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["training*", "tests*"]