[project]
name = "xarray"
version = "0.0.1a1"
requires-python = ">= 3.10"
dependencies = [
    "array_api_typing",
    "array_api_compat",
    "array_api_extra",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["training*", "tests*"]